//PRODUCTS
export const FETCH_ALL_PROJECTS = "FETCH_ALL_PROJECTS";
export const FETCH_ALL_PROJECTS_ERRORS = "FETCH_ALL_PROJECTS_ERROS";
export const FETCH_SINGLE_PROJECT = "FETCH_SINGLE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
//COMMENTS
export const FETCH_EXPENSES = "FETCH_EXPENSES";

//INCOME
export const CREATE_INCOME = "CREATE_INCOME";

//EXPENSES
export const CREATE_EXPENSE = "CREATE_EXPENSE";

//Users
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_MY_PROFILE = "GET_MY_PROFILE ";
export const EXPENSES_PROJECT_INCOME_CREATOR =
  "EXPENSES_INCOME_PROJECT_CREATOR";

//PROJECT TODO
export const CREATE_PROJECT_TODOS = "CREATE_PROJECT_TODOS";
export const FETCH_PROJECT_TODOS = "FETCH_PROJECT_TODOS";
export const FETCH_PROJECT_BY_USER_CODE = "FETCH_PROJECT_BY_USER_CODE";
